name: "Wait for Netlify"
description: "Wait for Netlify Deploy Preview to complete"
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_name:
    description: "The Netlify site name to test against"
    required: true
  request_headers:
    description: "Stringified HTTP Header object key/value pairs to send in requests"
    required: false
  max_timeout:
    description: "The max time to run the action"
    required: false
outputs:
  url:
    description: "The fully qualified deploy preview URL"
runs:
  using: "node12"
  main: "index.js"
